const PAISES: Record<string, { iso: string; emoji: string }> = {
  "Alemania": { iso: "DE", emoji: "🇩🇪" },
  "Arabia Saudita": { iso: "SA", emoji: "🇸🇦" },
  "Argelia": { iso: "DZ", emoji: "🇩🇿" },
  "Argentina": { iso: "AR", emoji: "🇦🇷" },
  "Australia": { iso: "AU", emoji: "🇦🇺" },
  "Austria": { iso: "AT", emoji: "🇦🇹" },
  "Bélgica": { iso: "BE", emoji: "🇧🇪" },
  "Bosnia y Herzegovina": { iso: "BA", emoji: "🇧🇦" },
  "Brasil": { iso: "BR", emoji: "🇧🇷" },
  "Cabo Verde": { iso: "CV", emoji: "🇨🇻" },
  "Canadá": { iso: "CA", emoji: "🇨🇦" },
  "Catar": { iso: "QA", emoji: "🇶🇦" },
  "Colombia": { iso: "CO", emoji: "🇨🇴" },
  "Congo DR": { iso: "CD", emoji: "🇨🇩" },
  "Corea del Sur": { iso: "KR", emoji: "🇰🇷" },
  "Costa de Marfil": { iso: "CI", emoji: "🇨🇮" },
  "Croacia": { iso: "HR", emoji: "🇭🇷" },
  "Curazao": { iso: "CW", emoji: "🇨🇼" },
  "Ecuador": { iso: "EC", emoji: "🇪🇨" },
  "Egipto": { iso: "EG", emoji: "🇪🇬" },
  "Escocia": { iso: "GB-SCT", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  "España": { iso: "ES", emoji: "🇪🇸" },
  "Estados Unidos": { iso: "US", emoji: "🇺🇸" },
  "Francia": { iso: "FR", emoji: "🇫🇷" },
  "Ghana": { iso: "GH", emoji: "🇬🇭" },
  "Haití": { iso: "HT", emoji: "🇭🇹" },
  "Inglaterra": { iso: "GB-ENG", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  "Irak": { iso: "IQ", emoji: "🇮🇶" },
  "Irán": { iso: "IR", emoji: "🇮🇷" },
  "Japón": { iso: "JP", emoji: "🇯🇵" },
  "Jordania": { iso: "JO", emoji: "🇯🇴" },
  "Marruecos": { iso: "MA", emoji: "🇲🇦" },
  "México": { iso: "MX", emoji: "🇲🇽" },
  "Noruega": { iso: "NO", emoji: "🇳🇴" },
  "Nueva Zelanda": { iso: "NZ", emoji: "🇳🇿" },
  "Panamá": { iso: "PA", emoji: "🇵🇦" },
  "Paraguay": { iso: "PY", emoji: "🇵🇾" },
  "Países Bajos": { iso: "NL", emoji: "🇳🇱" },
  "Portugal": { iso: "PT", emoji: "🇵🇹" },
  "República Checa": { iso: "CZ", emoji: "🇨🇿" },
  "Senegal": { iso: "SN", emoji: "🇸🇳" },
  "Sudáfrica": { iso: "ZA", emoji: "🇿🇦" },
  "Suecia": { iso: "SE", emoji: "🇸🇪" },
  "Suiza": { iso: "CH", emoji: "🇨🇭" },
  "Túnez": { iso: "TN", emoji: "🇹🇳" },
  "Turquía": { iso: "TR", emoji: "🇹🇷" },
  "Uruguay": { iso: "UY", emoji: "🇺🇾" },
  "Uzbekistán": { iso: "UZ", emoji: "🇺🇿" },
};

export function getPais(nombre: string) {
  return PAISES[nombre] ?? null;
}

export default PAISES;
